baseURL = "http://www.petraaxolotl.com"
languageCode = "en-us"
title = "All axolotls enjoy mathematics. But this one also loves physics."
theme = "gohugo-theme-ananke"
copyright = "Petra Axolotl"
sectionPagesMenu = "main"
favicon = "images/favicon.png"